"use strict";

/* 
    Music

      When on a videos list page, scroll to the bottom, then open the console and type:

  const vids = document.getElementsByClassName("yt-simple-endpoint focus-on-expand style-scope ytd-rich-grid-media");
  dict = {}; for (const vid of vids) {  
	let k = vid.getAttribute("aria-label");
	if (k.indexOf(" - ") != -1) {
		k = k.split(" - ")[1]
	}

	if (k.indexOf("(") != -1) {
		k = k.split("(")[0]
	}

	if (k.indexOf(" by ") != -1) {
		k = k.split(" by ")[0]
	}
	k = k.trim();
	const v = vid.getAttribute("href").split("=")[1];;
	dict[k] = v }; dict
  JSON.stringify(dict, 2, 2);

  To get a list 
*/

// from https://www.youtube.com/@TheAmbienceChannel
// these are under a Creative Commons License

const rpgAmbienceTracksString = `{
  "Underground Drill": "V4LMFa1fZGU&t",
  "Crowded Hall": "PuItqOyTDlk",
  "Jade Conquest": "t6mNGG6g378",
  "Ingvar's Mead": "Os1yu1ZXyUI",
  "Tyrant's March": "rA9nO-De1Zc",
  "Ghost Ship": "1NzLmREZqSY&t",
  "Through the Underworld": "vFR7QFVCkHs",
  "Serenity": "z3UB3yaJee4&t",
  "Courage": "owqcy7sfkE4",
  "They Are Coming": "L_BhK3C-u3g",
  "A Dangerous Quest": "eQFbkmHjx6I",
  "A City in the Distance": "UhyD0m5igv8",
  "Flooding City": "BaWvLbEHt28&t",
  "Bard College": "JzRclrjcHV8&t",
  "Orc Horde": "LA_usD5h640&t",
  "Marid / Water Genie Realms": "7phUzXCPmWc&t",
  "Dao / Earth Genie Realms": "80IXXagr_B4&t",
  "Djinn / Air Genie Realms": "ZHB-Yy_4dzU&t",
  "Mountain Camp": "18KN9L4VIGk",
  "Witch's Hut": "zIY_-M2lPJY&t",
  "Revolutionary War / 18th Century War": "bfGdYOKBZus",
  "Tropical Coast": "LboMqM5mEFA&t",
  "Haunted Battlefield": "QGQltGAWAU0&t",
  "Haunted House / Creepy Cabin": "QVQD9_eB8Qg",
  "Swamp Travel": "GpH6wKwOpy0&t",
  "Ghostly Procession": "wflzworJizA&t",
  "Monster Parade": "fXnIDBEa0Qs&t",
  "Firework Festival": "rkHA54puEhk&t",
  "Violent Storm": "B7PQv77VmSw&t",
  "Magical Catacombs": "pOm1dVXSqG0&t",
  "Viking Ship": "HB_1VXOQbEo&t",
  "Vampire Castle": "8tMZWESYXAA&t",
  "Preparing for a Trial": "sSTVlP1v6-M&t",
  "Royal Palace": "KTH8CuWEOvc&t",
  "Cursed City": "nI-iFEFCySE&t",
  "Mechanical Dungeon": "8lZWC0PwaLA&t",
  "Stables": "QZyoM1nXWRo&t",
  "Scroll Shop, Scribe's Office": "eYKWDUptWA4&t",
  "Ship Cabin": "iVLpFoo7ToA&t",
  "Burning Star": "4hLE7zm1yww",
  "Tavern Party": "x3skYa2i6Bg&t",
  "After a Battle / Empty Battlefield": "JElsb_pLXqg&t",
  "Collapsing Mine": "ou245Tc6tt4",
  "New Adventure": "5FVpHQJBeKM",
  "Empty Steppe": "345Cf-nsdnI",
  "Horse Carriage Chase": "WSoBRWF-Cw4&t",
  "Atlantis Underwater City": "T_4VNSHOnGU",
  "Giant's Forge": "PEtel5NTwAQ&t",
  "Training Ground": "DnmcTBFZRwU&t",
  "Autumn Night": "8Hr6QEQPhJY&t",
  "Flagellant Procession": "PdhVCPe3XA4",
  "Greek Maritime City": "dhQPzfmbjJE&t",
  "Horror from the Deep | Haunted Lighthouse": "_BUlHXNExPM",
  "Will-o'-the-Wisp Swamp": "nSm-RIO-1H8&t",
  "Eldritch Horror": "HYkhuvqkOdw&t",
  "Watefall": "sJr1JK3149M&t",
  "Public Whipping / Flogging": "2AsBiBm7YqA",
  "Autumn Forest": "TdBX9cjY2mA&t",
  "Practice Duel Sparring": "7DVo4NiYyUc",
  "Steppe / Savanna": "gXJM1L1cFpw&t",
  "Campfire Rest": "A1y09YspJvQ&t",
  "Acid Pool": "E-J9oPhdB5k&t",
  "Pagan Festival": "Z6six5WeZVY&t",
  "Brothel": "_ft7Nk2il_4&t",
  "Marching Through Rain": "nfK5wGJEjjs&t",
  "Giant Whirlpool": "3qo2dMkDEJk&t",
  "Abandoned Village": "FzzZ0Ll7UoA",
  "Peaceful Forest": "4B-tHXtHw_k",
  "Midsummer Festival": "50kEdch_4ao",
  "Coming of Angels": "G2Zmffr4iBU",
  "Water Mill": "l123ewMXptU",
  "Spider Cave": "qP9lmVaBhDI",
  "Inside a Monster": "G7HS6hP21LA",
  "City Gates": "u6q2mjSNuU0",
  "Sunset Forest": "mcuZQFauy0w",
  "Old Library": "1TwQY4dkWv0",
  "Winter War": "PFpAPHbYTWo",
  "Tavern Kitchen": "qJxSYTRxkiQ",
  "Slave Galley": "Rpim1NAFT18",
  "Winter River": "VqJ841bDbGo",
  "Making an Ambience": "K1AuH72oi5I",
  "End of the World": "fDogW8-RL-4",
  "Village Fire": "rVmIsBn_dyI",
  "Nighttime Inn": "-UmkWl4nvsk",
  "Torture Chambers": "lrZA4RoxO_M",
  "Ice Dragon": "7B9W6gFZNS0",
  "Trading Post": "gOyBE-oBicc",
  "Dangerous Forest": "LEs2J01gZX8",
  "Sick Bay": "1QLWFguij-Y",
  "Giant Sand Worm": "NkziO7QkExk&t",
  "Carriage in a Storm": "8HHtObBH0iE",
  "Cursed Wastes": "Af5-S2o7bcM",
  "Blood War": "Vx0bqo88XG8",
  "Elemental Chaos": "PPQtr5PDaL8",
  "Abyss": "aQLvd6h6WTM",
  "Slime Cave": "LZeNKZOXAOo",
  "Avernus [Descent Into Avernus]": "TTyOsAYD-Ng",
  "Kraken": "3hEY8hFQ55o",
  "Shipwreck": "z4sWBPr4wGM&t",
  "Jungle Ruins": "f6Ohca45lY4",
  "Garden Pond": "8Ic9-r417gs",
  "Cave City": "nfjrgINw0l4",
  "Clockwork Tower": "RukWUhWekcU",
  "Chariot Battle": "vXqVrspYuLs",
  "Forest City": "4dmPmVywWMw",
  "Giant's Rage": "rJlbizvKSGU",
  "Magic Realm": "-zyK1nv5l5s",
  "Giant Heart": "m3qV0ZvHLXU&t",
  "Valhalla | Eternal Battle": "3bY-zIGNZxs",
  "Steampunk Airship": "jFCTt0VH2R4",
  "Active Mine": "vnoLRJJJ8BQ",
  "Skeleton Horde": "IgoCbdd7yfY",
  "Lumber Mill": "EZJ4vU5aesc",
  "Ice Blizzard": "YyKW2EmGVO8",
  "Waiting in Ambush": "V7vl9iIZgMI",
  "Filthy Sewers": "7N5D5niaBWQ",
  "Bloody Slaughter": "TUKaKXdam9s",
  "Faerie Forest": "exf2967RCjg",
  "Knight Tournament": "Kws7g5Qqae0",
  "Ghostly Castle": "6A6IRkaNrx4",
  "Amazonian Baths": "DKYvu3hmH2Q",
  "Hydra": "CK4X-tNnR1M",
  "Jewelry Workshop": "uWcC1jlbwSA",
  "Earthquake": "9ta0_OKYADg",
  "Volcano Eruption": "lxNvXSpvc3s",
  "Orc Gang": "PxalDgmxAFo",
  "Underwater": "IaPEdWTPopA",
  "Ship in a Storm": "HoWVCG1H_bg",
  "Lighthouse Fire": "mXbwarVE52U",
  "Treasure Cave": "8jA_Q0oHSrg",
  "Holy Temple": "BTVkNq072UE",
  "Military Encampment": "J-1JR8lU1is",
  "Forest Battle": "thnSlpl5pIU",
  "Burning Forest": "mOMOX0FoKP4",
  "Public Bathhouse": "bPyLzYYugn0",
  "Cozy Home": "V7PpeZzltLI",
  "Empty Tavern": "H01x22_PKok",
  "Dwarven Smithy": "7LqWV3KZcPo",
  "Human Sacrifice": "OKY_wpP-ZAo",
  "Naval Battle": "RoBjokc-s8M",
  "Tavern Bard": "an6-eSSAIM8",
  "Scary Forest": "BkmO28ihl2Y",
  "Fiery Volcano": "kUhDNbBPPhQ",
  "Horse Archer": "gD8o7ShYnXo",
  "Horse Cart": "-bP2oZy9Kjg",
  "Beast Lands": "tZSLkRLreFQ",
  "Sword Duel": "oBsHWwmXbcM",
  "Mayan / Amerindian City": "7sEI8_MW16Q",
  "Banshee's Cry": "PJ7ePH9eVZ0",
  "Harpy Nest": "bXujtcFHcxc",
  "Summer Night": "kSK2iyMS8GY",
  "Dragon's Rampage": "26Byt2pNV4M",
  "Werewolf Forest": "128kAIlwh4g",
  "Giant's Home": "HkCSrnsd2F8",
  "Plague & Disease": "p2tO8lNCRRI",
  "Dark Prison": "gbYGvsTSk9k",
  "Tavern Brawl": "wo1Z8DdOrqA",
  "Pilgrim's Path": "xcdBdAUXo3Y",
  "Tribal Charge": "g-qPRt4IRMo",
  "Stealthy Burglary": "SXYLUuEjbqk",
  "Druid's Cave": "W3Ep_LocbAY",
  "Town Panic": "Sw9yC8rKcAY",
  "World Tree": "J2RiEp-M4Og",
  "Magic Academy": "nd3nIxU3g7Y",
  "Hookah Den": "q5dQT7-Xoh0",
  "Artisan Street": "Hoba6ktJ1NA",
  "Warriors of the Dunes": "6aA1Jh0ohd4",
  "Street Preacher": "glnsdpLN-40",
  "Electric Dragon": "qXAkVD4qvHY",
  "Castle Guard": "J5HWAUgwITg",
  "River Boat": "UxNILOXJVhM",
  "Roman Lavatory": "XgZivLuAnaU",
  "Archer Volleys": "tELTUn9jP5M",
  "Village Barn": "V5l2SxH6RgY",
  "Dragon's Lair": "4BAdhivcV90",
  "Battle Charge": "Bz0Cye__3AQ",
  "Monster Infested Caves": "nNpDCYUaaFg",
  "Desert Winds": "_5SwTjctJ-w",
  "Underground Forge": "gsn1HnI1pCQ",
  "Nesting Cliffs": "9I3ShuKYiFk",
  "Canyon Bridge": "8WrKG28WTVM",
  "Undead Crypt": "QVtwZW7YQik",
  "Monument Construction": "gJpb9I3I1N8",
  "Clock Tower": "6XQZWTfS5CE",
  "Ice City": "6XTV76qBtCs",
  "Desert Canyon": "4ovTEOsPnCk",
  "War Dance": "EQIrzBh1EIk",
  "Royal Treasury": "QgJsoaUdHys",
  "Alchemist's Lab": "KWbo3PslD-M",
  "Medieval Feast": "klIstouu6pU",
  "Rainy Funeral": "aio5v9Fs870",
  "Snake Temple": "8wvtDdEWqms",
  "Buzzing Hive": "oZ2aCy43AOI",
  "Misty Swamp": "LC4am6qDWrk",
  "Eldritch Spell": "cuUb08zzBTY",
  "Nomad Camp": "pmuRfU8RS0A",
  "Ancient Tomb": "FWYqxqXkyXc",
  "Pirate Harbour": "h8dL9Igch60",
  "Tribunal of the Dead": "BzpdJXyR9Io",
  "Insanity Mansion": "qHsUQSRaqpg",
  "Secret Cult": "HuKBWPd-PI4",
  "Battle March": "MGQDtF_-UvE",
  "Thunder Forge": "N5M6stAd8uY",
  "Great Caravan": "_LmC4aDniAM",
  "Long Road": "PtktRQWAcxQ",
  "Frantic Chase": "bzHqm-AyaNM",
  "Public Execution": "oRP9mnTkgac",
  "Secluded Monastery": "wSUgTrA4u4M",
  "Sailing Ship": "pzn9t1Me6qk",
  "Heavenly Abode": "-LpBf87xuEw",
  "Crowded Tavern": "cbs558TPI3I",
  "Wild Tribe": "Ys5KpQSEsG8",
  "Slave Mines": "y6a66O0LIwE",
  "Spring Forest": "lJpJRygR6vQ",
  "Magical Vortex": "VzUVQMWyrWE",
  "Rowdy Arena": "OvX9YrCg0K4",
  "Burning Pits": "5Ze-4Ez0mXc",
  "Dreadful Hunt": "vNHisdJfBKA",
  "Lush Jungle": "2X71luNaHQc",
  "Joyful Festival": "gcPSA3sUilc",
  "Solemn Temple": "4ZDht1QyTjc",
  "Busy Market": "6ksms45EOIg",
  "Haunted Graveyard": "Ll0vtrU2oaI",
  "Calm Sea": "wm6AaLi-pzQ",
  "Raging Battle": "JEUTQJzKef4",
  "Winter Forest": "vuc0LK4LNWI"
}`;

function rpgAmbienceTracksDict() {
  return JSON.parse(rpgAmbienceTracksString);
}

rpgAmbienceTracksDict(); // just a test

// TODO:
// add https://www.youtube.com/@AjsDnDMusic/videos




